# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.7.2 on Wed Apr 25 15:34:07 2018
#

import wx
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class ABotFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ABotFrame.__init__
        wx.Frame.__init__(self, *args, **kwds)
        self.MainNotebook = wx.Notebook(self, wx.ID_ANY)
        self.MainNotebook_connect_pane = wx.Panel(self.MainNotebook, wx.ID_ANY)
        self.label_1 = wx.StaticText(self.MainNotebook_connect_pane, wx.ID_ANY, "Available interfaces")
        self.choice_interfaces = wx.Choice(self.MainNotebook_connect_pane, wx.ID_ANY, choices=["USB0"])
        self.button_interface_connect = wx.Button(self.MainNotebook_connect_pane, wx.ID_ANY, "Connect")
        self.list_ctrl_1 = wx.ListCtrl(self.MainNotebook_connect_pane, wx.ID_ANY)
        self.MainNotebook_pane_1 = wx.Panel(self.MainNotebook, wx.ID_ANY)
        self.label_2 = wx.StaticText(self.MainNotebook_pane_1, wx.ID_ANY, "X axis")
        self.spin_ctrl_x = wx.SpinCtrl(self.MainNotebook_pane_1, wx.ID_ANY, "", min=0, max=9200)
        self.button_1 = wx.Button(self.MainNotebook_pane_1, wx.ID_ANY, "Home")
        self.button_6 = wx.Button(self.MainNotebook_pane_1, wx.ID_ANY, "Move")
        self.label_3 = wx.StaticText(self.MainNotebook_pane_1, wx.ID_ANY, "Y axis")
        self.spin_ctrl_y = wx.SpinCtrl(self.MainNotebook_pane_1, wx.ID_ANY, "", min=0, max=13640)
        self.button_2 = wx.Button(self.MainNotebook_pane_1, wx.ID_ANY, "Home")
        self.button_7 = wx.Button(self.MainNotebook_pane_1, wx.ID_ANY, "Move")
        self.label_4 = wx.StaticText(self.MainNotebook_pane_1, wx.ID_ANY, "Z axis")
        self.spin_ctrl_z = wx.SpinCtrl(self.MainNotebook_pane_1, wx.ID_ANY, "", min=0, max=7000)
        self.button_3 = wx.Button(self.MainNotebook_pane_1, wx.ID_ANY, "Home")
        self.button_8 = wx.Button(self.MainNotebook_pane_1, wx.ID_ANY, "Move")
        self.label_5 = wx.StaticText(self.MainNotebook_pane_1, wx.ID_ANY, "Piston")
        self.spin_ctrl_p = wx.SpinCtrl(self.MainNotebook_pane_1, wx.ID_ANY, "", min=0, max=36000)
        self.button_4 = wx.Button(self.MainNotebook_pane_1, wx.ID_ANY, "Up")
        self.button_5 = wx.Button(self.MainNotebook_pane_1, wx.ID_ANY, "Down")
        self.button_9 = wx.Button(self.MainNotebook_pane_1, wx.ID_ANY, "Move")
        self.MainNotebook_pane_2 = wx.Panel(self.MainNotebook, wx.ID_ANY)
        self.label_6 = wx.StaticText(self.MainNotebook_pane_2, wx.ID_ANY, "Spot 1")
        self.text_ctrl_tspot1 = wx.TextCtrl(self.MainNotebook_pane_2, wx.ID_ANY, "", style=wx.TE_READONLY)
        self.button_10 = wx.Button(self.MainNotebook_pane_2, wx.ID_ANY, "Import")
        self.button_14 = wx.Button(self.MainNotebook_pane_2, wx.ID_ANY, "Update")
        self.label_7 = wx.StaticText(self.MainNotebook_pane_2, wx.ID_ANY, "Spot 2")
        self.text_ctrl_tspot2 = wx.TextCtrl(self.MainNotebook_pane_2, wx.ID_ANY, "", style=wx.TE_READONLY)
        self.button_11 = wx.Button(self.MainNotebook_pane_2, wx.ID_ANY, "Import")
        self.button_15 = wx.Button(self.MainNotebook_pane_2, wx.ID_ANY, "Update")
        self.label_8 = wx.StaticText(self.MainNotebook_pane_2, wx.ID_ANY, "Spot 3")
        self.text_ctrl_tspot3 = wx.TextCtrl(self.MainNotebook_pane_2, wx.ID_ANY, "", style=wx.TE_READONLY)
        self.button_12 = wx.Button(self.MainNotebook_pane_2, wx.ID_ANY, "Import")
        self.button_16 = wx.Button(self.MainNotebook_pane_2, wx.ID_ANY, "Update")
        self.label_9 = wx.StaticText(self.MainNotebook_pane_2, wx.ID_ANY, "Spot 4")
        self.text_ctrl_tspot4 = wx.TextCtrl(self.MainNotebook_pane_2, wx.ID_ANY, "", style=wx.TE_READONLY)
        self.button_13 = wx.Button(self.MainNotebook_pane_2, wx.ID_ANY, "Import")
        self.button_17 = wx.Button(self.MainNotebook_pane_2, wx.ID_ANY, "Update")
        self.MainNotebook_pane_3 = wx.Panel(self.MainNotebook, wx.ID_ANY)
        self.radio_box_op_spot = wx.RadioBox(self.MainNotebook_pane_3, wx.ID_ANY, "Spot", choices=["1", "2", "3", "4"], majorDimension=1, style=wx.RA_SPECIFY_COLS)
        self.label_10 = wx.StaticText(self.MainNotebook_pane_3, wx.ID_ANY, "Row")
        self.text_ctrl_op_row = wx.TextCtrl(self.MainNotebook_pane_3, wx.ID_ANY, "")
        self.label_11 = wx.StaticText(self.MainNotebook_pane_3, wx.ID_ANY, "Column")
        self.text_ctrl_op_col = wx.TextCtrl(self.MainNotebook_pane_3, wx.ID_ANY, "")
        self.label_12 = wx.StaticText(self.MainNotebook_pane_3, wx.ID_ANY, "Tip position")
        self.text_ctrl_op_tip = wx.TextCtrl(self.MainNotebook_pane_3, wx.ID_ANY, "")
        self.label_13 = wx.StaticText(self.MainNotebook_pane_3, wx.ID_ANY, "Volume")
        self.text_ctrl_op_vol = wx.TextCtrl(self.MainNotebook_pane_3, wx.ID_ANY, "")
        self.button_18 = wx.Button(self.MainNotebook_pane_3, wx.ID_ANY, "Move")
        self.button_19 = wx.Button(self.MainNotebook_pane_3, wx.ID_ANY, "Aspirate")
        self.button_20 = wx.Button(self.MainNotebook_pane_3, wx.ID_ANY, "Dispense")
        self.button_21 = wx.Button(self.MainNotebook_pane_3, wx.ID_ANY, "Purge")
        self.button_22 = wx.Button(self.MainNotebook_pane_3, wx.ID_ANY, "Wash")
        self.button_23 = wx.Button(self.MainNotebook_pane_3, wx.ID_ANY, "Home")
        self.MainNotebook_pane_5 = wx.Panel(self.MainNotebook, wx.ID_ANY)
        self.button_stepXm = wx.Button(self.MainNotebook_pane_5, wx.ID_ANY, "Decrease")
        self.choice_xm = wx.Choice(self.MainNotebook_pane_5, wx.ID_ANY, choices=["2", "4", "8", "16", "32", "64", "128", "256", "512", "1024"])
        self.button_stepXm1000 = wx.Button(self.MainNotebook_pane_5, wx.ID_ANY, "-1000", style=wx.BU_EXACTFIT)
        self.button_stepXm100 = wx.Button(self.MainNotebook_pane_5, wx.ID_ANY, "-100", style=wx.BU_EXACTFIT)
        self.button_stepXm10 = wx.Button(self.MainNotebook_pane_5, wx.ID_ANY, "-10", style=wx.BU_EXACTFIT)
        self.button_stepXm1 = wx.Button(self.MainNotebook_pane_5, wx.ID_ANY, "-1", style=wx.BU_EXACTFIT)
        self.label_stepperX = wx.StaticText(self.MainNotebook_pane_5, wx.ID_ANY, "X=", style=wx.ALIGN_LEFT)
        self.button_stepXp1 = wx.Button(self.MainNotebook_pane_5, wx.ID_ANY, "+1", style=wx.BU_EXACTFIT)
        self.button_stepXp10 = wx.Button(self.MainNotebook_pane_5, wx.ID_ANY, "+10", style=wx.BU_EXACTFIT)
        self.button_stepXp100 = wx.Button(self.MainNotebook_pane_5, wx.ID_ANY, "+100", style=wx.BU_EXACTFIT)
        self.button_stepXp1000 = wx.Button(self.MainNotebook_pane_5, wx.ID_ANY, "+1000", style=wx.BU_EXACTFIT)
        self.choice_xp = wx.Choice(self.MainNotebook_pane_5, wx.ID_ANY, choices=["2", "4", "8", "16", "32", "64", "128", "256", "512", "1024"])
        self.button_stepXp = wx.Button(self.MainNotebook_pane_5, wx.ID_ANY, "Increase")
        self.button_stepYm = wx.Button(self.MainNotebook_pane_5, wx.ID_ANY, "Decrease")
        self.choice_ym = wx.Choice(self.MainNotebook_pane_5, wx.ID_ANY, choices=["2", "4", "8", "16", "32", "64", "128", "256", "512", "1024"])
        self.button_stepYm1000 = wx.Button(self.MainNotebook_pane_5, wx.ID_ANY, "-1000", style=wx.BU_EXACTFIT)
        self.button_stepYm100 = wx.Button(self.MainNotebook_pane_5, wx.ID_ANY, "-100", style=wx.BU_EXACTFIT)
        self.button_stepYm10 = wx.Button(self.MainNotebook_pane_5, wx.ID_ANY, "-10", style=wx.BU_EXACTFIT)
        self.button_stepYm1 = wx.Button(self.MainNotebook_pane_5, wx.ID_ANY, "-1", style=wx.BU_EXACTFIT)
        self.label_stepperY = wx.StaticText(self.MainNotebook_pane_5, wx.ID_ANY, "Y=", style=wx.ALIGN_LEFT)
        self.button_stepYp1 = wx.Button(self.MainNotebook_pane_5, wx.ID_ANY, "+1", style=wx.BU_EXACTFIT)
        self.button_stepYp10 = wx.Button(self.MainNotebook_pane_5, wx.ID_ANY, "+10", style=wx.BU_EXACTFIT)
        self.button_stepYp100 = wx.Button(self.MainNotebook_pane_5, wx.ID_ANY, "+100", style=wx.BU_EXACTFIT)
        self.button_stepYp1000 = wx.Button(self.MainNotebook_pane_5, wx.ID_ANY, "+1000", style=wx.BU_EXACTFIT)
        self.choice_yp = wx.Choice(self.MainNotebook_pane_5, wx.ID_ANY, choices=["2", "4", "8", "16", "32", "64", "128", "256", "512", "1024"])
        self.button_stepYp = wx.Button(self.MainNotebook_pane_5, wx.ID_ANY, "Increase")
        self.button_stepZm = wx.Button(self.MainNotebook_pane_5, wx.ID_ANY, "Decrease")
        self.choice_zm = wx.Choice(self.MainNotebook_pane_5, wx.ID_ANY, choices=["2", "4", "8", "16", "32", "64", "128", "256", "512", "1024"])
        self.button_stepZm1000 = wx.Button(self.MainNotebook_pane_5, wx.ID_ANY, "-1000", style=wx.BU_EXACTFIT)
        self.button_stepZm100 = wx.Button(self.MainNotebook_pane_5, wx.ID_ANY, "-100", style=wx.BU_EXACTFIT)
        self.button_stepZm10 = wx.Button(self.MainNotebook_pane_5, wx.ID_ANY, "-10", style=wx.BU_EXACTFIT)
        self.button_stepZm1 = wx.Button(self.MainNotebook_pane_5, wx.ID_ANY, "-1", style=wx.BU_EXACTFIT)
        self.label_stepperZ = wx.StaticText(self.MainNotebook_pane_5, wx.ID_ANY, "Z=", style=wx.ALIGN_LEFT)
        self.button_stepZp1 = wx.Button(self.MainNotebook_pane_5, wx.ID_ANY, "+1", style=wx.BU_EXACTFIT)
        self.button_stepZp10 = wx.Button(self.MainNotebook_pane_5, wx.ID_ANY, "+10", style=wx.BU_EXACTFIT)
        self.button_stepZp100 = wx.Button(self.MainNotebook_pane_5, wx.ID_ANY, "+100", style=wx.BU_EXACTFIT)
        self.button_stepZp1000 = wx.Button(self.MainNotebook_pane_5, wx.ID_ANY, "+1000", style=wx.BU_EXACTFIT)
        self.choice_zp = wx.Choice(self.MainNotebook_pane_5, wx.ID_ANY, choices=["2", "4", "8", "16", "32", "64", "128", "256", "512", "1024"])
        self.button_stepZp = wx.Button(self.MainNotebook_pane_5, wx.ID_ANY, "Increase")
        self.button_stepVm = wx.Button(self.MainNotebook_pane_5, wx.ID_ANY, "Decrease")
        self.choice_vm = wx.Choice(self.MainNotebook_pane_5, wx.ID_ANY, choices=["2", "4", "8", "16", "32", "64", "128", "256", "512", "1024"])
        self.button_stepVm1000 = wx.Button(self.MainNotebook_pane_5, wx.ID_ANY, "-1000", style=wx.BU_EXACTFIT)
        self.button_stepVm100 = wx.Button(self.MainNotebook_pane_5, wx.ID_ANY, "-100", style=wx.BU_EXACTFIT)
        self.button_stepVm10 = wx.Button(self.MainNotebook_pane_5, wx.ID_ANY, "-10", style=wx.BU_EXACTFIT)
        self.button_stepVm1 = wx.Button(self.MainNotebook_pane_5, wx.ID_ANY, "-1", style=wx.BU_EXACTFIT)
        self.label_stepperV = wx.StaticText(self.MainNotebook_pane_5, wx.ID_ANY, "V=", style=wx.ALIGN_LEFT)
        self.button_stepVp1 = wx.Button(self.MainNotebook_pane_5, wx.ID_ANY, "+1", style=wx.BU_EXACTFIT)
        self.button_stepVp10 = wx.Button(self.MainNotebook_pane_5, wx.ID_ANY, "+10", style=wx.BU_EXACTFIT)
        self.button_stepVp100 = wx.Button(self.MainNotebook_pane_5, wx.ID_ANY, "+100", style=wx.BU_EXACTFIT)
        self.button_stepVp1000 = wx.Button(self.MainNotebook_pane_5, wx.ID_ANY, "+1000", style=wx.BU_EXACTFIT)
        self.choice_vp = wx.Choice(self.MainNotebook_pane_5, wx.ID_ANY, choices=["2", "4", "8", "16", "32", "64", "128", "256", "512", "1024"])
        self.button_stepVp = wx.Button(self.MainNotebook_pane_5, wx.ID_ANY, "Increase")
        self.MainFrame_statusbar = self.CreateStatusBar(1)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.wxBotConnect, self.button_interface_connect)
        self.Bind(wx.EVT_BUTTON, self.wxXHome, self.button_1)
        self.Bind(wx.EVT_BUTTON, self.wxXMove, self.button_6)
        self.Bind(wx.EVT_BUTTON, self.wxYHome, self.button_2)
        self.Bind(wx.EVT_BUTTON, self.wxYMove, self.button_7)
        self.Bind(wx.EVT_BUTTON, self.wxZHome, self.button_3)
        self.Bind(wx.EVT_BUTTON, self.wxZMove, self.button_8)
        self.Bind(wx.EVT_BUTTON, self.wxPHomeUp, self.button_4)
        self.Bind(wx.EVT_BUTTON, self.wxPHomeDn, self.button_5)
        self.Bind(wx.EVT_BUTTON, self.wxPMove, self.button_9)
        self.Bind(wx.EVT_BUTTON, self.wxImportSpot1, self.button_10)
        self.Bind(wx.EVT_BUTTON, self.wxUpdateSpot1, self.button_14)
        self.Bind(wx.EVT_BUTTON, self.wxImportSpot2, self.button_11)
        self.Bind(wx.EVT_BUTTON, self.wxUpdateSpot2, self.button_15)
        self.Bind(wx.EVT_BUTTON, self.wxImportSpot3, self.button_12)
        self.Bind(wx.EVT_BUTTON, self.wxUpdateSpot3, self.button_16)
        self.Bind(wx.EVT_BUTTON, self.wxImportSpot4, self.button_13)
        self.Bind(wx.EVT_BUTTON, self.wxUpdateSpot4, self.button_17)
        self.Bind(wx.EVT_BUTTON, self.wxOperateMove, self.button_18)
        self.Bind(wx.EVT_BUTTON, self.wxOperateAspirate, self.button_19)
        self.Bind(wx.EVT_BUTTON, self.wxOperateDispense, self.button_20)
        self.Bind(wx.EVT_BUTTON, self.wxOperatePurge, self.button_21)
        self.Bind(wx.EVT_BUTTON, self.wxOperateWash, self.button_22)
        self.Bind(wx.EVT_BUTTON, self.wxOperateHome, self.button_23)
        self.Bind(wx.EVT_BUTTON, self.onStepXm, self.button_stepXm)
        self.Bind(wx.EVT_BUTTON, self.onStepXm1000, self.button_stepXm1000)
        self.Bind(wx.EVT_BUTTON, self.onStepXm100, self.button_stepXm100)
        self.Bind(wx.EVT_BUTTON, self.onStepXm10, self.button_stepXm10)
        self.Bind(wx.EVT_BUTTON, self.onStepXm1, self.button_stepXm1)
        self.Bind(wx.EVT_BUTTON, self.onStepXp1, self.button_stepXp1)
        self.Bind(wx.EVT_BUTTON, self.onStepXp10, self.button_stepXp10)
        self.Bind(wx.EVT_BUTTON, self.onStepXp100, self.button_stepXp100)
        self.Bind(wx.EVT_BUTTON, self.onStepXp1000, self.button_stepXp1000)
        self.Bind(wx.EVT_BUTTON, self.onStepXp, self.button_stepXp)
        self.Bind(wx.EVT_BUTTON, self.onStepYm, self.button_stepYm)
        self.Bind(wx.EVT_BUTTON, self.onStepYm1000, self.button_stepYm1000)
        self.Bind(wx.EVT_BUTTON, self.onStepYm100, self.button_stepYm100)
        self.Bind(wx.EVT_BUTTON, self.onStepYm10, self.button_stepYm10)
        self.Bind(wx.EVT_BUTTON, self.onStepYm1, self.button_stepYm1)
        self.Bind(wx.EVT_BUTTON, self.onStepYp1, self.button_stepYp1)
        self.Bind(wx.EVT_BUTTON, self.onStepYp10, self.button_stepYp10)
        self.Bind(wx.EVT_BUTTON, self.onStepYp100, self.button_stepYp100)
        self.Bind(wx.EVT_BUTTON, self.onStepYp1000, self.button_stepYp1000)
        self.Bind(wx.EVT_BUTTON, self.onStepYp, self.button_stepYp)
        self.Bind(wx.EVT_BUTTON, self.onStepZm, self.button_stepZm)
        self.Bind(wx.EVT_BUTTON, self.onStepZm1000, self.button_stepZm1000)
        self.Bind(wx.EVT_BUTTON, self.onStepZm100, self.button_stepZm100)
        self.Bind(wx.EVT_BUTTON, self.onStepZm10, self.button_stepZm10)
        self.Bind(wx.EVT_BUTTON, self.onStepZm1, self.button_stepZm1)
        self.Bind(wx.EVT_BUTTON, self.onStepZp1, self.button_stepZp1)
        self.Bind(wx.EVT_BUTTON, self.onStepZp10, self.button_stepZp10)
        self.Bind(wx.EVT_BUTTON, self.onStepZp100, self.button_stepZp100)
        self.Bind(wx.EVT_BUTTON, self.onStepZp1000, self.button_stepZp1000)
        self.Bind(wx.EVT_BUTTON, self.onStepZp, self.button_stepZp)
        self.Bind(wx.EVT_BUTTON, self.onStepVm, self.button_stepVm)
        self.Bind(wx.EVT_BUTTON, self.onStepVm1000, self.button_stepVm1000)
        self.Bind(wx.EVT_BUTTON, self.onStepVm100, self.button_stepVm100)
        self.Bind(wx.EVT_BUTTON, self.onStepVm10, self.button_stepVm10)
        self.Bind(wx.EVT_BUTTON, self.onStepVm1, self.button_stepVm1)
        self.Bind(wx.EVT_BUTTON, self.onStepVp1, self.button_stepVp1)
        self.Bind(wx.EVT_BUTTON, self.onStepVp10, self.button_stepVp10)
        self.Bind(wx.EVT_BUTTON, self.onStepVp100, self.button_stepVp100)
        self.Bind(wx.EVT_BUTTON, self.onStepVp1000, self.button_stepVp1000)
        self.Bind(wx.EVT_BUTTON, self.onStepVp, self.button_stepVp)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: ABotFrame.__set_properties
        self.SetTitle("Apribot GUI")
        self.choice_interfaces.SetSelection(0)
        self.radio_box_op_spot.SetSelection(0)
        self.choice_xm.SetSelection(0)
        self.choice_xp.SetSelection(0)
        self.choice_ym.SetSelection(0)
        self.choice_yp.SetSelection(0)
        self.choice_zm.SetSelection(0)
        self.choice_zp.SetSelection(0)
        self.choice_vm.SetSelection(0)
        self.choice_vp.SetSelection(0)
        self.MainFrame_statusbar.SetStatusWidths([-1])

        # statusbar fields
        MainFrame_statusbar_fields = ["MainFrame_statusbar"]
        for i in range(len(MainFrame_statusbar_fields)):
            self.MainFrame_statusbar.SetStatusText(MainFrame_statusbar_fields[i], i)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: ABotFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_4 = wx.GridSizer(4, 13, 1, 1)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_6 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_3 = wx.GridSizer(4, 2, 1, 1)
        grid_sizer_2 = wx.GridSizer(4, 4, 1, 1)
        grid_sizer_1 = wx.GridSizer(4, 4, 1, 1)
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_3.Add(self.label_1, 0, 0, 0)
        sizer_3.Add(self.choice_interfaces, 0, 0, 0)
        sizer_3.Add(self.button_interface_connect, 0, 0, 0)
        sizer_2.Add(sizer_3, 1, 0, 0)
        sizer_2.Add(self.list_ctrl_1, 1, 0, 0)
        self.MainNotebook_connect_pane.SetSizer(sizer_2)
        grid_sizer_1.Add(self.label_2, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.spin_ctrl_x, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.button_1, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.button_6, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.label_3, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.spin_ctrl_y, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.button_2, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.button_7, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.label_4, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.spin_ctrl_z, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.button_3, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.button_8, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.label_5, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.spin_ctrl_p, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_5.Add(self.button_4, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_5.Add(self.button_5, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(sizer_5, 1, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.button_9, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        self.MainNotebook_pane_1.SetSizer(grid_sizer_1)
        grid_sizer_2.Add(self.label_6, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_2.Add(self.text_ctrl_tspot1, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_2.Add(self.button_10, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_2.Add(self.button_14, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_2.Add(self.label_7, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_2.Add(self.text_ctrl_tspot2, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_2.Add(self.button_11, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_2.Add(self.button_15, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_2.Add(self.label_8, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_2.Add(self.text_ctrl_tspot3, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_2.Add(self.button_12, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_2.Add(self.button_16, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_2.Add(self.label_9, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_2.Add(self.text_ctrl_tspot4, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_2.Add(self.button_13, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_2.Add(self.button_17, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        self.MainNotebook_pane_2.SetSizer(grid_sizer_2)
        sizer_4.Add(self.radio_box_op_spot, 0, 0, 5)
        grid_sizer_3.Add(self.label_10, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_3.Add(self.text_ctrl_op_row, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_3.Add(self.label_11, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_3.Add(self.text_ctrl_op_col, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_3.Add(self.label_12, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_3.Add(self.text_ctrl_op_tip, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_3.Add(self.label_13, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_3.Add(self.text_ctrl_op_vol, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_4.Add(grid_sizer_3, 1, 0, 5)
        sizer_6.Add(self.button_18, 0, 0, 0)
        sizer_6.Add(self.button_19, 0, 0, 0)
        sizer_6.Add(self.button_20, 0, 0, 0)
        sizer_6.Add(self.button_21, 0, 0, 0)
        sizer_6.Add(self.button_22, 0, 0, 0)
        sizer_6.Add(self.button_23, 0, 0, 0)
        sizer_4.Add(sizer_6, 1, 0, 5)
        self.MainNotebook_pane_3.SetSizer(sizer_4)
        grid_sizer_4.Add(self.button_stepXm, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_4.Add(self.choice_xm, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_4.Add(self.button_stepXm1000, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_4.Add(self.button_stepXm100, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_4.Add(self.button_stepXm10, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_4.Add(self.button_stepXm1, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_4.Add(self.label_stepperX, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_4.Add(self.button_stepXp1, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_4.Add(self.button_stepXp10, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_4.Add(self.button_stepXp100, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_4.Add(self.button_stepXp1000, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_4.Add(self.choice_xp, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_4.Add(self.button_stepXp, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_4.Add(self.button_stepYm, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_4.Add(self.choice_ym, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_4.Add(self.button_stepYm1000, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_4.Add(self.button_stepYm100, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_4.Add(self.button_stepYm10, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_4.Add(self.button_stepYm1, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_4.Add(self.label_stepperY, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_4.Add(self.button_stepYp1, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_4.Add(self.button_stepYp10, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_4.Add(self.button_stepYp100, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_4.Add(self.button_stepYp1000, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_4.Add(self.choice_yp, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_4.Add(self.button_stepYp, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_4.Add(self.button_stepZm, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_4.Add(self.choice_zm, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_4.Add(self.button_stepZm1000, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_4.Add(self.button_stepZm100, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_4.Add(self.button_stepZm10, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_4.Add(self.button_stepZm1, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_4.Add(self.label_stepperZ, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_4.Add(self.button_stepZp1, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_4.Add(self.button_stepZp10, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_4.Add(self.button_stepZp100, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_4.Add(self.button_stepZp1000, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_4.Add(self.choice_zp, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_4.Add(self.button_stepZp, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_4.Add(self.button_stepVm, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_4.Add(self.choice_vm, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_4.Add(self.button_stepVm1000, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_4.Add(self.button_stepVm100, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_4.Add(self.button_stepVm10, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_4.Add(self.button_stepVm1, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_4.Add(self.label_stepperV, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_4.Add(self.button_stepVp1, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_4.Add(self.button_stepVp10, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_4.Add(self.button_stepVp100, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_4.Add(self.button_stepVp1000, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_4.Add(self.choice_vp, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_4.Add(self.button_stepVp, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        self.MainNotebook_pane_5.SetSizer(grid_sizer_4)
        self.MainNotebook.AddPage(self.MainNotebook_connect_pane, "Connect")
        self.MainNotebook.AddPage(self.MainNotebook_pane_1, "Manual")
        self.MainNotebook.AddPage(self.MainNotebook_pane_2, "Stage")
        self.MainNotebook.AddPage(self.MainNotebook_pane_3, "Operate")
        self.MainNotebook.AddPage(self.MainNotebook_pane_5, "Stepper")
        sizer_1.Add(self.MainNotebook, 1, 0, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

    def wxBotConnect(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'wxBotConnect' not implemented!"
        event.Skip()

    def wxXHome(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'wxXHome' not implemented!"
        event.Skip()

    def wxXMove(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'wxXMove' not implemented!"
        event.Skip()

    def wxYHome(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'wxYHome' not implemented!"
        event.Skip()

    def wxYMove(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'wxYMove' not implemented!"
        event.Skip()

    def wxZHome(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'wxZHome' not implemented!"
        event.Skip()

    def wxZMove(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'wxZMove' not implemented!"
        event.Skip()

    def wxPHomeUp(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'wxPHomeUp' not implemented!"
        event.Skip()

    def wxPHomeDn(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'wxPHomeDn' not implemented!"
        event.Skip()

    def wxPMove(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'wxPMove' not implemented!"
        event.Skip()

    def wxImportSpot1(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'wxImportSpot1' not implemented!"
        event.Skip()

    def wxUpdateSpot1(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'wxUpdateSpot1' not implemented!"
        event.Skip()

    def wxImportSpot2(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'wxImportSpot2' not implemented!"
        event.Skip()

    def wxUpdateSpot2(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'wxUpdateSpot2' not implemented!"
        event.Skip()

    def wxImportSpot3(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'wxImportSpot3' not implemented!"
        event.Skip()

    def wxUpdateSpot3(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'wxUpdateSpot3' not implemented!"
        event.Skip()

    def wxImportSpot4(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'wxImportSpot4' not implemented!"
        event.Skip()

    def wxUpdateSpot4(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'wxUpdateSpot4' not implemented!"
        event.Skip()

    def wxOperateMove(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'wxOperateMove' not implemented!"
        event.Skip()

    def wxOperateAspirate(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'wxOperateAspirate' not implemented!"
        event.Skip()

    def wxOperateDispense(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'wxOperateDispense' not implemented!"
        event.Skip()

    def wxOperatePurge(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'wxOperatePurge' not implemented!"
        event.Skip()

    def wxOperateWash(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'wxOperateWash' not implemented!"
        event.Skip()

    def wxOperateHome(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'wxOperateHome' not implemented!"
        event.Skip()

    def onStepXm(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'onStepXm' not implemented!"
        event.Skip()

    def onStepXm1000(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'onStepXm1000' not implemented!"
        event.Skip()

    def onStepXm100(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'onStepXm100' not implemented!"
        event.Skip()

    def onStepXm10(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'onStepXm10' not implemented!"
        event.Skip()

    def onStepXm1(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'onStepXm1' not implemented!"
        event.Skip()

    def onStepXp1(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'onStepXp1' not implemented!"
        event.Skip()

    def onStepXp10(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'onStepXp10' not implemented!"
        event.Skip()

    def onStepXp100(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'onStepXp100' not implemented!"
        event.Skip()

    def onStepXp1000(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'onStepXp1000' not implemented!"
        event.Skip()

    def onStepXp(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'onStepXp' not implemented!"
        event.Skip()

    def onStepYm(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'onStepYm' not implemented!"
        event.Skip()

    def onStepYm1000(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'onStepYm1000' not implemented!"
        event.Skip()

    def onStepYm100(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'onStepYm100' not implemented!"
        event.Skip()

    def onStepYm10(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'onStepYm10' not implemented!"
        event.Skip()

    def onStepYm1(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'onStepYm1' not implemented!"
        event.Skip()

    def onStepYp1(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'onStepYp1' not implemented!"
        event.Skip()

    def onStepYp10(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'onStepYp10' not implemented!"
        event.Skip()

    def onStepYp100(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'onStepYp100' not implemented!"
        event.Skip()

    def onStepYp1000(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'onStepYp1000' not implemented!"
        event.Skip()

    def onStepYp(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'onStepYp' not implemented!"
        event.Skip()

    def onStepZm(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'onStepZm' not implemented!"
        event.Skip()

    def onStepZm1000(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'onStepZm1000' not implemented!"
        event.Skip()

    def onStepZm100(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'onStepZm100' not implemented!"
        event.Skip()

    def onStepZm10(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'onStepZm10' not implemented!"
        event.Skip()

    def onStepZm1(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'onStepZm1' not implemented!"
        event.Skip()

    def onStepZp1(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'onStepZp1' not implemented!"
        event.Skip()

    def onStepZp10(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'onStepZp10' not implemented!"
        event.Skip()

    def onStepZp100(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'onStepZp100' not implemented!"
        event.Skip()

    def onStepZp1000(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'onStepZp1000' not implemented!"
        event.Skip()

    def onStepZp(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'onStepZp' not implemented!"
        event.Skip()

    def onStepVm(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'onStepVm' not implemented!"
        event.Skip()

    def onStepVm1000(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'onStepVm1000' not implemented!"
        event.Skip()

    def onStepVm100(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'onStepVm100' not implemented!"
        event.Skip()

    def onStepVm10(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'onStepVm10' not implemented!"
        event.Skip()

    def onStepVm1(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'onStepVm1' not implemented!"
        event.Skip()

    def onStepVp1(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'onStepVp1' not implemented!"
        event.Skip()

    def onStepVp10(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'onStepVp10' not implemented!"
        event.Skip()

    def onStepVp100(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'onStepVp100' not implemented!"
        event.Skip()

    def onStepVp1000(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'onStepVp1000' not implemented!"
        event.Skip()

    def onStepVp(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'onStepVp' not implemented!"
        event.Skip()

# end of class ABotFrame
