# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.7.1 on Tue Oct 10 15:49:39 2017
#

import wx
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class ABotFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ABotFrame.__init__
        wx.Frame.__init__(self, *args, **kwds)
        self.MainNotebook = wx.Notebook(self, wx.ID_ANY)
        self.MainNotebook_connect_pane = wx.Panel(self.MainNotebook, wx.ID_ANY)
        self.label_1 = wx.StaticText(self.MainNotebook_connect_pane, wx.ID_ANY, "Available interfaces")
        self.choice_interfaces = wx.Choice(self.MainNotebook_connect_pane, wx.ID_ANY, choices=["USB0"])
        self.button_interface_connect = wx.Button(self.MainNotebook_connect_pane, wx.ID_ANY, "Connect")
        self.list_ctrl_1 = wx.ListCtrl(self.MainNotebook_connect_pane, wx.ID_ANY)
        self.MainNotebook_pane_1 = wx.Panel(self.MainNotebook, wx.ID_ANY)
        self.label_2 = wx.StaticText(self.MainNotebook_pane_1, wx.ID_ANY, "X axis")
        self.spin_ctrl_x = wx.SpinCtrl(self.MainNotebook_pane_1, wx.ID_ANY, "", min=0, max=9200)
        self.button_1 = wx.Button(self.MainNotebook_pane_1, wx.ID_ANY, "Home")
        self.button_6 = wx.Button(self.MainNotebook_pane_1, wx.ID_ANY, "Move")
        self.label_3 = wx.StaticText(self.MainNotebook_pane_1, wx.ID_ANY, "Y axis")
        self.spin_ctrl_y = wx.SpinCtrl(self.MainNotebook_pane_1, wx.ID_ANY, "", min=0, max=13640)
        self.button_2 = wx.Button(self.MainNotebook_pane_1, wx.ID_ANY, "Home")
        self.button_7 = wx.Button(self.MainNotebook_pane_1, wx.ID_ANY, "Move")
        self.label_4 = wx.StaticText(self.MainNotebook_pane_1, wx.ID_ANY, "Z axis")
        self.spin_ctrl_z = wx.SpinCtrl(self.MainNotebook_pane_1, wx.ID_ANY, "", min=0, max=7000)
        self.button_3 = wx.Button(self.MainNotebook_pane_1, wx.ID_ANY, "Home")
        self.button_8 = wx.Button(self.MainNotebook_pane_1, wx.ID_ANY, "Move")
        self.label_5 = wx.StaticText(self.MainNotebook_pane_1, wx.ID_ANY, "Piston")
        self.spin_ctrl_p = wx.SpinCtrl(self.MainNotebook_pane_1, wx.ID_ANY, "", min=0, max=36000)
        self.button_4 = wx.Button(self.MainNotebook_pane_1, wx.ID_ANY, "Up")
        self.button_5 = wx.Button(self.MainNotebook_pane_1, wx.ID_ANY, "Down")
        self.button_9 = wx.Button(self.MainNotebook_pane_1, wx.ID_ANY, "Move")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.wxBotConnect, self.button_interface_connect)
        self.Bind(wx.EVT_BUTTON, self.wxXHome, self.button_1)
        self.Bind(wx.EVT_BUTTON, self.wxXMove, self.button_6)
        self.Bind(wx.EVT_BUTTON, self.wxYHome, self.button_2)
        self.Bind(wx.EVT_BUTTON, self.wxYMove, self.button_7)
        self.Bind(wx.EVT_BUTTON, self.wxZHome, self.button_3)
        self.Bind(wx.EVT_BUTTON, self.wxZMove, self.button_8)
        self.Bind(wx.EVT_BUTTON, self.wxPHomeUp, self.button_4)
        self.Bind(wx.EVT_BUTTON, self.wxPHomeDn, self.button_5)
        self.Bind(wx.EVT_BUTTON, self.wxPMove, self.button_9)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: ABotFrame.__set_properties
        self.SetTitle("Apribot GUI")
        self.choice_interfaces.SetSelection(0)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: ABotFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_1 = wx.GridSizer(4, 4, 1, 1)
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_3.Add(self.label_1, 0, 0, 0)
        sizer_3.Add(self.choice_interfaces, 0, 0, 0)
        sizer_3.Add(self.button_interface_connect, 0, 0, 0)
        sizer_2.Add(sizer_3, 1, 0, 0)
        sizer_2.Add(self.list_ctrl_1, 1, 0, 0)
        self.MainNotebook_connect_pane.SetSizer(sizer_2)
        grid_sizer_1.Add(self.label_2, 0, 0, 0)
        grid_sizer_1.Add(self.spin_ctrl_x, 0, 0, 0)
        grid_sizer_1.Add(self.button_1, 0, 0, 0)
        grid_sizer_1.Add(self.button_6, 0, 0, 0)
        grid_sizer_1.Add(self.label_3, 0, 0, 0)
        grid_sizer_1.Add(self.spin_ctrl_y, 0, 0, 0)
        grid_sizer_1.Add(self.button_2, 0, 0, 0)
        grid_sizer_1.Add(self.button_7, 0, 0, 0)
        grid_sizer_1.Add(self.label_4, 0, 0, 0)
        grid_sizer_1.Add(self.spin_ctrl_z, 0, 0, 0)
        grid_sizer_1.Add(self.button_3, 0, 0, 0)
        grid_sizer_1.Add(self.button_8, 0, 0, 0)
        grid_sizer_1.Add(self.label_5, 0, 0, 0)
        grid_sizer_1.Add(self.spin_ctrl_p, 0, 0, 0)
        sizer_5.Add(self.button_4, 0, 0, 0)
        sizer_5.Add(self.button_5, 0, 0, 0)
        grid_sizer_1.Add(sizer_5, 1, 0, 0)
        grid_sizer_1.Add(self.button_9, 0, 0, 0)
        self.MainNotebook_pane_1.SetSizer(grid_sizer_1)
        self.MainNotebook.AddPage(self.MainNotebook_connect_pane, "Connect")
        self.MainNotebook.AddPage(self.MainNotebook_pane_1, "Manual")
        sizer_1.Add(self.MainNotebook, 1, 0, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

    def wxBotConnect(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'wxBotConnect' not implemented!"
        event.Skip()

    def wxXHome(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'wxXHome' not implemented!"
        event.Skip()

    def wxXMove(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'wxXMove' not implemented!"
        event.Skip()

    def wxYHome(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'wxYHome' not implemented!"
        event.Skip()

    def wxYMove(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'wxYMove' not implemented!"
        event.Skip()

    def wxZHome(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'wxZHome' not implemented!"
        event.Skip()

    def wxZMove(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'wxZMove' not implemented!"
        event.Skip()

    def wxPHomeUp(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'wxPHomeUp' not implemented!"
        event.Skip()

    def wxPHomeDn(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'wxPHomeDn' not implemented!"
        event.Skip()

    def wxPMove(self, event):  # wxGlade: ABotFrame.<event_handler>
        print "Event handler 'wxPMove' not implemented!"
        event.Skip()

# end of class ABotFrame
